config/routes.rb
require 'api_constraints'

BeerBuilder::Application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :ingredient_yeasts, :only => [:index, :show]
      resources :ingredient_grains, :only => [:index, :show]
      resources :ingredient_hops, :only => [:index, :show]
      resources :tags, :only => [:index, :show]
      resources :beer_categories, :only => [:index, :show]
      resources :beer_styles, :only => [:index, :show]
      resources :prototypes, :only => [:index, :show]
      resources :yeasts, :only => [:index, :show]
      resources :hops, :only => [:index, :show]
      resources :grains, :only => [:index, :show]    
    end
  end

  resources :ingredient_yeasts

  resources :ingredient_grains

  resources :ingredient_hops

  resources :tags

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  devise_for :admins

  resources :beer_categories

  resources :beer_styles

  resources :prototypes

  resources :yeasts

  resources :hops

  resources :grains

  root :to => "beer_categories#index"

end

app/models/beer_style.rb
class BeerStyle
  include Mongoid::Document
  field :name, type: String
  field :og_hi, type: BigDecimal
  field :og_lo, type: BigDecimal
  field :fg_lo, type: BigDecimal
  field :fg_hi, type: BigDecimal
  field :abv_lo, type: BigDecimal
  field :abv_hi, type: BigDecimal
  field :ibu_lo, type: BigDecimal
  field :ibu_hi, type: BigDecimal
  field :srm_lo, type: BigDecimal
  field :srm_hi, type: BigDecimal
  field :aroma, type: String
  field :appearance, type: String
  field :flavor, type: String
  field :mouthfeel, type: String
  field :overall_impression, type: String
  field :comments, type: String
  field :history, type: String

  belongs_to :beer_category
  has_many :prototypes
  accepts_nested_attributes_for :prototypes

  validates :name, presence:true
end

app/controllers/api/v1/beer_styles_controller.rb
module Api
  module V1
    class BeerStylesController < ApplicationController
      respond_to :json
      def index
        respond_with BeerStyle.all
      end
      
      def show
        respond_with BeerStyle.find(params[:id])
      end
    end
  end
end

app/controllers/beer_styles_controller.rb
class BeerStylesController < ApplicationController
  # GET /beer_styles
  # GET /beer_styles.json
  def index
    @beer_styles = BeerStyle.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beer_styles }
    end
  end

  # GET /beer_styles/1
  # GET /beer_styles/1.json
  def show
    @beer_style = BeerStyle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer_style }
    end
  end

  # GET /beer_styles/new
  # GET /beer_styles/new.json
  def new
    @beer_style = BeerStyle.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer_style }
    end
  end

  # GET /beer_styles/1/edit
  def edit
    @beer_style = BeerStyle.find(params[:id])
  end

  # POST /beer_styles
  # POST /beer_styles.json
  def create
    @beer_style = BeerStyle.new(params[:beer_style])

    respond_to do |format|
      if @beer_style.save
        format.html { redirect_to @beer_style, notice: 'Beer style was successfully created.' }
        format.json { render json: @beer_style, status: :created, location: @beer_style }
      else
        format.html { render action: "new" }
        format.json { render json: @beer_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beer_styles/1
  # PUT /beer_styles/1.json
  def update
    @beer_style = BeerStyle.find(params[:id])

    respond_to do |format|
      if @beer_style.update_attributes(params[:beer_style])
        format.html { redirect_to @beer_style, notice: 'Beer style was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_styles/1
  # DELETE /beer_styles/1.json
  def destroy
    @beer_style = BeerStyle.find(params[:id])
    @beer_style.destroy

    respond_to do |format|
      format.html { redirect_to beer_styles_url }
      format.json { head :ok }
    end
  end
end

app/helpers/beer_styles_helper.rb
module BeerStylesHelper
end

app/views/beer_styles/_form.html.erb
<%= form_for(@beer_style) do |f| %>
  <% if @beer_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_style.errors.count, "error") %> prohibited this beer_style from being saved:</h2>

      <ul>
      <% @beer_style.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :og_hi %><br />
    <%= f.text_field :og_hi %>
  </div>
  <div class="field">
    <%= f.label :og_lo %><br />
    <%= f.text_field :og_lo %>
  </div>
  <div class="field">
    <%= f.label :fg_lo %><br />
    <%= f.text_field :fg_lo %>
  </div>
  <div class="field">
    <%= f.label :fg_hi %><br />
    <%= f.text_field :fg_hi %>
  </div>
  <div class="field">
    <%= f.label :abv_lo %><br />
    <%= f.text_field :abv_lo %>
  </div>
  <div class="field">
    <%= f.label :abv_hi %><br />
    <%= f.text_field :abv_hi %>
  </div>
  <div class="field">
    <%= f.label :ibu_lo %><br />
    <%= f.text_field :ibu_lo %>
  </div>
  <div class="field">
    <%= f.label :ibu_hi %><br />
    <%= f.text_field :ibu_hi %>
  </div>
  <div class="field">
    <%= f.label :srm_lo %><br />
    <%= f.text_field :srm_lo %>
  </div>
  <div class="field">
    <%= f.label :srm_hi %><br />
    <%= f.text_field :srm_hi %>
  </div>
  <div class="field">
    <%= f.label :aroma %><br />
    <%= f.text_area :aroma %>
  </div>
  <div class="field">
    <%= f.label :appearance %><br />
    <%= f.text_area :appearance %>
  </div>
  <div class="field">
    <%= f.label :flavor %><br />
    <%= f.text_area :flavor %>
  </div>
  <div class="field">
    <%= f.label :mouthfeel %><br />
    <%= f.text_area :mouthfeel %>
  </div>
  <div class="field">
    <%= f.label :overall_impression %><br />
    <%= f.text_area :overall_impression %>
  </div>
  <div class="field">
    <%= f.label :comments %><br />
    <%= f.text_area :comments %>
  </div>
  <div class="field">
    <%= f.label :history %><br />
    <%= f.text_area :history %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_styles/edit.html.erb
<h1>Editing beer_style</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_style %> |
<%= link_to 'Back', beer_styles_path %>

app/views/beer_styles/index.html.erb
<h1>Listing beer_styles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Og hi</th>
    <th>Og lo</th>
    <th>Fg lo</th>
    <th>Fg hi</th>
    <th>Abv lo</th>
    <th>Abv hi</th>
    <th>Ibu lo</th>
    <th>Ibu hi</th>
    <th>Srm lo</th>
    <th>Srm hi</th>
    <th>Aroma</th>
    <th>Appearance</th>
    <th>Flavor</th>
    <th>Mouthfeel</th>
    <th>Overall impression</th>
    <th>Comments</th>
    <th>History</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beer_styles.each do |beer_style| %>
  <tr>
    <td><%= beer_style.name %></td>
    <td><%= beer_style.og_hi %></td>
    <td><%= beer_style.og_lo %></td>
    <td><%= beer_style.fg_lo %></td>
    <td><%= beer_style.fg_hi %></td>
    <td><%= beer_style.abv_lo %></td>
    <td><%= beer_style.abv_hi %></td>
    <td><%= beer_style.ibu_lo %></td>
    <td><%= beer_style.ibu_hi %></td>
    <td><%= beer_style.srm_lo %></td>
    <td><%= beer_style.srm_hi %></td>
    <td><%= beer_style.aroma %></td>
    <td><%= beer_style.appearance %></td>
    <td><%= beer_style.flavor %></td>
    <td><%= beer_style.mouthfeel %></td>
    <td><%= beer_style.overall_impression %></td>
    <td><%= beer_style.comments %></td>
    <td><%= beer_style.history %></td>
    <td><%= link_to 'Show', beer_style %></td>
    <td><%= link_to 'Edit', edit_beer_style_path(beer_style) %></td>
    <td><%= link_to 'Destroy', beer_style, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer style', new_beer_style_path %>

app/views/beer_styles/new.html.erb
<h1>New beer_style</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_styles_path %>

app/views/beer_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer_style.name %>
</p>

<p>
  <b>Og hi:</b>
  <%= @beer_style.og_hi %>
</p>

<p>
  <b>Og lo:</b>
  <%= @beer_style.og_lo %>
</p>

<p>
  <b>Fg lo:</b>
  <%= @beer_style.fg_lo %>
</p>

<p>
  <b>Fg hi:</b>
  <%= @beer_style.fg_hi %>
</p>

<p>
  <b>Abv lo:</b>
  <%= @beer_style.abv_lo %>
</p>

<p>
  <b>Abv hi:</b>
  <%= @beer_style.abv_hi %>
</p>

<p>
  <b>Ibu lo:</b>
  <%= @beer_style.ibu_lo %>
</p>

<p>
  <b>Ibu hi:</b>
  <%= @beer_style.ibu_hi %>
</p>

<p>
  <b>Srm lo:</b>
  <%= @beer_style.srm_lo %>
</p>

<p>
  <b>Srm hi:</b>
  <%= @beer_style.srm_hi %>
</p>

<p>
  <b>Aroma:</b>
  <%= @beer_style.aroma %>
</p>

<p>
  <b>Appearance:</b>
  <%= @beer_style.appearance %>
</p>

<p>
  <b>Flavor:</b>
  <%= @beer_style.flavor %>
</p>

<p>
  <b>Mouthfeel:</b>
  <%= @beer_style.mouthfeel %>
</p>

<p>
  <b>Overall impression:</b>
  <%= @beer_style.overall_impression %>
</p>

<p>
  <b>Comments:</b>
  <%= @beer_style.comments %>
</p>

<p>
  <b>History:</b>
  <%= @beer_style.history %>
</p>


<%= link_to 'Edit', edit_beer_style_path(@beer_style) %> |
<%= link_to 'Back', beer_styles_path %>