config/routes.rb
require 'api_constraints'

BeerBuilder::Application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :ingredient_yeasts, :only => [:index, :show]
      resources :ingredient_grains, :only => [:index, :show]
      resources :ingredient_hops, :only => [:index, :show]
      resources :tags, :only => [:index, :show]
      resources :beer_categories, :only => [:index, :show]
      resources :beer_styles, :only => [:index, :show]
      resources :prototypes, :only => [:index, :show]
      resources :yeasts, :only => [:index, :show]
      resources :hops, :only => [:index, :show]
      resources :grains, :only => [:index, :show]    
    end
  end

  resources :ingredient_yeasts

  resources :ingredient_grains

  resources :ingredient_hops

  resources :tags

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  devise_for :admins

  resources :beer_categories

  resources :beer_styles

  resources :prototypes

  resources :yeasts

  resources :hops

  resources :grains

  root :to => "beer_categories#index"

end

app/models/beer_category.rb
class BeerCategory
  include Mongoid::Document
  include Mongoid::Timestamps::Updated

  field :name, type: String

  has_many :beer_styles, :inverse_of => :beer_category
  has_many :prototypes, :inverse_of => :beer_category
end

app/controllers/api/v1/beer_categories_controller.rb
module Api
  module V1
    class BeerCategoriesController < ApplicationController
      before_filter :ensure_updated_data
      respond_to :json
      def index
        respond_with BeerCategory.all
      end
      
      def show
        respond_with BeerCategory.find(params[:id])
      end
    end
  end
end

app/controllers/beer_categories_controller.rb
class BeerCategoriesController < ApplicationController
  # GET /beer_categories
  # GET /beer_categories.json
  def index
    @beer_categories = BeerCategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @beer_categories }
    end
  end

  # GET /beer_categories/1
  # GET /beer_categories/1.json
  def show
    @beer_category = BeerCategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @beer_category }
    end
  end

  # GET /beer_categories/new
  # GET /beer_categories/new.json
  def new
    @beer_category = BeerCategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @beer_category }
    end
  end

  # GET /beer_categories/1/edit
  def edit
    @beer_category = BeerCategory.find(params[:id])
  end

  # POST /beer_categories
  # POST /beer_categories.json
  def create
    @beer_category = BeerCategory.new(params[:beer_category])

    respond_to do |format|
      if @beer_category.save
        format.html { redirect_to @beer_category, notice: 'Beer category was successfully created.' }
        format.json { render json: @beer_category, status: :created, location: @beer_category }
      else
        format.html { render action: "new" }
        format.json { render json: @beer_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /beer_categories/1
  # PUT /beer_categories/1.json
  def update
    @beer_category = BeerCategory.find(params[:id])

    respond_to do |format|
      if @beer_category.update_attributes(params[:beer_category])
        format.html { redirect_to @beer_category, notice: 'Beer category was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @beer_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beer_categories/1
  # DELETE /beer_categories/1.json
  def destroy
    @beer_category = BeerCategory.find(params[:id])
    @beer_category.destroy

    respond_to do |format|
      format.html { redirect_to beer_categories_url }
      format.json { head :ok }
    end
  end
end

app/helpers/beer_categories_helper.rb
module BeerCategoriesHelper
end

app/views/beer_categories/_form.html.erb
<%= form_for(@beer_category) do |f| %>
  <% if @beer_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer_category.errors.count, "error") %> prohibited this beer_category from being saved:</h2>

      <ul>
      <% @beer_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beer_categories/edit.html.erb
<h1>Editing beer_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer_category %> |
<%= link_to 'Back', beer_categories_path %>

app/views/beer_categories/index.html.erb
<h1>Listing beer_categories</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @beer_categories.each do |beer_category| %>
  <tr>
    <td><%= beer_category.name %></td>
    <td><%= link_to 'Show', beer_category %></td>
    <td><%= link_to 'Edit', edit_beer_category_path(beer_category) %></td>
    <td><%= link_to 'Destroy', beer_category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Beer category', new_beer_category_path %>

app/views/beer_categories/new.html.erb
<h1>New beer_category</h1>

<%= render 'form' %>

<%= link_to 'Back', beer_categories_path %>

app/views/beer_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @beer_category.name %>
</p>


<%= link_to 'Edit', edit_beer_category_path(@beer_category) %> |
<%= link_to 'Back', beer_categories_path %>