config/routes.rb
require 'api_constraints'

BeerBuilder::Application.routes.draw do
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :ingredient_yeasts, :only => [:index, :show]
      resources :ingredient_grains, :only => [:index, :show]
      resources :ingredient_hops, :only => [:index, :show]
      resources :tags, :only => [:index, :show]
      resources :beer_categories, :only => [:index, :show]
      resources :beer_styles, :only => [:index, :show]
      resources :prototypes, :only => [:index, :show]
      resources :yeasts, :only => [:index, :show]
      resources :hops, :only => [:index, :show]
      resources :grains, :only => [:index, :show]    
    end
  end

  resources :ingredient_yeasts

  resources :ingredient_grains

  resources :ingredient_hops

  resources :tags

  mount RailsAdmin::Engine => '/superadmin', :as => 'rails_admin'

  devise_for :admins

  resources :beer_categories

  resources :beer_styles

  resources :prototypes

  resources :yeasts

  resources :hops

  resources :grains

  root :to => "beer_categories#index"

end

app/models/yeast.rb
class Yeast
  include Mongoid::Document
  include Mongoid::Timestamps::Updated
  field :name, type: String
  field :attenuation_lo, type: BigDecimal
  field :attenuation_hi, type: BigDecimal
  field :flocculation, type: BigDecimal
  field :temperature_lo, type: BigDecimal
  field :temperature_hi, type: BigDecimal
  field :alcohol_tolerance, type: BigDecimal

  validates :name, presence:true

  has_many :tags
end

app/controllers/api/v1/yeasts_controller.rb
module Api
  module V1
    class YeastsController < ApplicationController
      before_filter :ensure_updated_data
      respond_to :json
      def index
        respond_with Yeast.all
      end
      
      def show
        respond_with Yeast.find(params[:id])
      end
    end
  end
end

app/controllers/yeasts_controller.rb
class YeastsController < ApplicationController
  # GET /yeasts
  # GET /yeasts.json
  def index
    @yeasts = Yeast.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @yeasts }
    end
  end

  # GET /yeasts/1
  # GET /yeasts/1.json
  def show
    @yeast = Yeast.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @yeast }
    end
  end

  # GET /yeasts/new
  # GET /yeasts/new.json
  def new
    @yeast = Yeast.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @yeast }
    end
  end

  # GET /yeasts/1/edit
  def edit
    @yeast = Yeast.find(params[:id])
  end

  # POST /yeasts
  # POST /yeasts.json
  def create
    @yeast = Yeast.new(params[:yeast])

    respond_to do |format|
      if @yeast.save
        format.html { redirect_to @yeast, notice: 'Yeast was successfully created.' }
        format.json { render json: @yeast, status: :created, location: @yeast }
      else
        format.html { render action: "new" }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /yeasts/1
  # PUT /yeasts/1.json
  def update
    @yeast = Yeast.find(params[:id])

    respond_to do |format|
      if @yeast.update_attributes(params[:yeast])
        format.html { redirect_to @yeast, notice: 'Yeast was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @yeast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /yeasts/1
  # DELETE /yeasts/1.json
  def destroy
    @yeast = Yeast.find(params[:id])
    @yeast.destroy

    respond_to do |format|
      format.html { redirect_to yeasts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/yeasts_helper.rb
module YeastsHelper
end

app/views/yeasts/_form.html.erb
<%= form_for(@yeast) do |f| %>
  <% if @yeast.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@yeast.errors.count, "error") %> prohibited this yeast from being saved:</h2>

      <ul>
      <% @yeast.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :attenuation_lo %><br />
    <%= f.text_field :attenuation_lo %>
  </div>
  <div class="field">
    <%= f.label :attenuation_hi %><br />
    <%= f.text_field :attenuation_hi %>
  </div>
  <div class="field">
    <%= f.label :flocculation %><br />
    <%= f.text_field :flocculation %>
  </div>
  <div class="field">
    <%= f.label :temperature_lo %><br />
    <%= f.text_field :temperature_lo %>
  </div>
  <div class="field">
    <%= f.label :temperature_hi %><br />
    <%= f.text_field :temperature_hi %>
  </div>
  <div class="field">
    <%= f.label :alcohol_tolerance %><br />
    <%= f.text_field :alcohol_tolerance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/yeasts/edit.html.erb
<h1>Editing yeast</h1>

<%= render 'form' %>

<%= link_to 'Show', @yeast %> |
<%= link_to 'Back', yeasts_path %>

app/views/yeasts/index.html.erb
<h1>Listing yeasts</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Attenuation lo</th>
    <th>Attenuation hi</th>
    <th>Flocculation</th>
    <th>Temperature lo</th>
    <th>Temperature hi</th>
    <th>Alcohol tolerance</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @yeasts.each do |yeast| %>
  <tr>
    <td><%= yeast.name %></td>
    <td><%= yeast.attenuation_lo %></td>
    <td><%= yeast.attenuation_hi %></td>
    <td><%= yeast.flocculation %></td>
    <td><%= yeast.temperature_lo %></td>
    <td><%= yeast.temperature_hi %></td>
    <td><%= yeast.alcohol_tolerance %></td>
    <td><%= link_to 'Show', yeast %></td>
    <td><%= link_to 'Edit', edit_yeast_path(yeast) %></td>
    <td><%= link_to 'Destroy', yeast, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Yeast', new_yeast_path %>

app/views/yeasts/new.html.erb
<h1>New yeast</h1>

<%= render 'form' %>

<%= link_to 'Back', yeasts_path %>

app/views/yeasts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @yeast.name %>
</p>

<p>
  <b>Attenuation lo:</b>
  <%= @yeast.attenuation_lo %>
</p>

<p>
  <b>Attenuation hi:</b>
  <%= @yeast.attenuation_hi %>
</p>

<p>
  <b>Flocculation:</b>
  <%= @yeast.flocculation %>
</p>

<p>
  <b>Temperature lo:</b>
  <%= @yeast.temperature_lo %>
</p>

<p>
  <b>Temperature hi:</b>
  <%= @yeast.temperature_hi %>
</p>

<p>
  <b>Alcohol tolerance:</b>
  <%= @yeast.alcohol_tolerance %>
</p>


<%= link_to 'Edit', edit_yeast_path(@yeast) %> |
<%= link_to 'Back', yeasts_path %>